import { NextResponse } from 'next/server';

export async function POST(req: Request) {
    try {
        const { prompt } = await req.json();

        // TODO: Integrate OpenAI/Gemini here if user provides key.
        // For now, return a valid Magic JAML mock based on the prompt.

        console.log("🧞 Genie Request:", prompt);

        const mockJaml = `
# Generated by JAML Genie (Local Mock)
# Prompt: ${prompt}

filter:
  should:
    - joker: Blueprint
    - joker: Brainstorm
    - tag: Investment Tag
  
  must:
    - ante: <= 2
      has: 
        - joker: Blueprint
`;

        return NextResponse.json({ jaml: mockJaml });
    } catch (error) {
        return NextResponse.json({ error: "Genie Malfunction" }, { status: 500 });
    }
}
